--- #YAML:1.0
name:               stockmonkey
version:            2.9014
abstract:           ~
author:  []
license:            LGPL
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    constant:  1.05
    perl:      5.006001
resources:
    repository:  http://github.com/jettero/stockmonkey
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - ATR
    - bollinger-bands
    - DMI
    - EMA
    - HMA
    - MACD
    - RSI
    - SMA
    - WMU
    - ParabolicSAR
    - LaguerreFilter
