---
abstract: unknown
author:
  - 'Paul Miller <jettero@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.96, CPAN::Meta::Converter version 2.140640'
keywords:
  - ATR
  - bollinger
  - bands
  - CCI
  - DMI
  - EMA
  - HMA
  - MACD
  - RSI
  - SMA
  - WMU
  - ParabolicSAR
  - Laguerre
  - Stochastic
  - ConnorRSI
  - CRSI
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: stockmonkey
no_index:
  directory:
    - t
    - inc
requires:
  Math::Business::Stochastic: '0'
  constant: '1.05'
  perl: '5.006001'
resources:
  repository: http://github.com/jettero/stockmonkey
version: '2.9405'
