---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
keywords:
  - ATR
  - bollinger-bands
  - DMI
  - EMA
  - HMA
  - MACD
  - RSI
  - SMA
  - WMU
  - ParabolicSAR
  - LaguerreFilter
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: stockmonkey
no_index:
  directory:
    - t
    - inc
requires:
  constant: 1.05
  perl: 5.006001
resources:
  repository: http://github.com/jettero/stockmonkey
version: 2.9015
